version: "3.8"

services:
  manager:
    build:
      context: .
      dockerfile: manager/Dockerfile
    container_name: manager
    ports:
      - "8080:8080"

  worker1:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker1
    ports:
      - "8081:8081"
    depends_on:
      - manager

  worker2:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker2
    ports:
      - "8082:8081"
    depends_on:
      - manager

  worker3:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker3
    ports:
      - "8083:8081"
    depends_on:
      - manager
